---
title: "96M Metals WQS"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```


```{r, include=FALSE}
library(gWQS)
library(broom)
library(broom.mixed)
library(qgcomp)
library(gt)
library(tidyverse)
library(readxl)
library(readr)
library(data.table)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(gtsummary)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(modelr)
library(readr)


urine_whole <- read_csv("~/Projects/Mixture second/input/intermediate/urine_whole.csv")
urine_subset <- read_csv("~/Projects/Mixture second/input/intermediate/urine_subset.csv")

label(urine_whole$Panel2_q_Albumin) <- "Albumin"
label(urine_whole$Panel2_q_Cystatin_C) <-"CystatinC"
label(urine_whole$Panel1_q_KIM_1) <-"KIM1"
label(urine_whole$Panel2_q_Lipocalin) <-"Lipocalin"
label(urine_whole$Panel2_q_A1_Microglobulin) <-"A1M"
label(urine_whole$Panel3_q_X2Microglobulin) <-"X2M"
label(urine_whole$Panel3_q_RBP) <-"RBP"
label(urine_whole$Panel2_q_OPN) <-"OPN"
label(urine_whole$Panel3_q_Uromodulin) <-"Uromodulin"
label(urine_whole$Panel3_mfi_Uromodulin) <-"Uromodulin mfi"
label(urine_whole$Panel1_q_GSTa) <- "GSTa"

label(urine_subset$Panel2_q_Albumin) <- "Albumin"
label(urine_subset$Panel2_q_Cystatin_C) <-"CystatinC"
label(urine_subset$Panel1_q_KIM_1) <-"KIM1"
label(urine_subset$Panel2_q_Lipocalin) <-"Lipocalin"
label(urine_subset$Panel2_q_A1_Microglobulin) <-"A1M"
label(urine_subset$Panel3_q_X2Microglobulin) <-"X2M"
label(urine_subset$Panel3_q_RBP) <-"RBP"
label(urine_subset$Panel2_q_OPN) <-"OPN"
label(urine_subset$Panel3_q_Uromodulin) <-"Uromodulin"
label(urine_subset$Panel3_mfi_Uromodulin) <-"Uromodulin mfi"
label(urine_subset$Panel1_q_GSTa) <- "GSTa"

```

# check protein distributions in our sample
## Table
### Untransformed
```{r}
## untransformed
urine_whole_table<- urine_whole %>% 
                    tbl_summary(
                      include = c(Panel2_q_Albumin, Panel2_q_Cystatin_C, Panel1_q_KIM_1, Panel2_q_Lipocalin, Panel2_q_A1_Microglobulin, Panel3_q_X2Microglobulin, Panel3_q_RBP, Panel2_q_OPN, Panel3_q_Uromodulin, Panel3_mfi_Uromodulin, Panel1_q_GSTa),
                      statistic = list(all_continuous() ~ "{median} ({p25}, {p75}) [{min} - {max}]"),
                      missing_text = "Missing"
                    ) %>% 
                    bold_labels()

## log2 transformed
urine_subset_table<- urine_subset %>% 
                    tbl_summary(
                      include = c(Panel2_q_Albumin, Panel2_q_Cystatin_C, Panel1_q_KIM_1, Panel2_q_Lipocalin, Panel2_q_A1_Microglobulin, Panel3_q_X2Microglobulin, Panel3_q_RBP, Panel2_q_OPN, Panel3_q_Uromodulin, Panel3_mfi_Uromodulin, Panel1_q_GSTa),
                      statistic = list(all_continuous() ~ "{median} ({p25}, {p75}) [{min} - {max}]"),
                      missing_text = "Missing"
                    ) %>% 
                    bold_labels()

urine_table<- tbl_merge(tbls = list(urine_whole_table,urine_subset_table),
                              tab_spanner = c("**Whole**", "**Subset**"))  %>%
              modify_caption("**Untransformed Protein values**")%>%               
              as_gt() %>%
              tab_footnote(footnote = "Exclude loss to follow-up; missing  96M urine metals; missing SES, BMI, smoking at visit, age and creatinine",
                           locations = cells_column_spanners(
                                       spanners = "**Whole**"
                            )) %>%
              tab_footnote(footnote = "Further exlude those gestational age < 37 and >42 weeks",
                           locations = cells_column_spanners(
                                       spanners =  "**Subset**"
                            ))

urine_table

```

### Log2-transformed
```{r}
## untransformed
urine_whole_table<- urine_whole %>% 
                    tbl_summary(
                      include = c(Albumin, CystatinC, KIM1, Lipocalin, A1M, X2M, RBP, OPN, Uromodulin, Uromodulin_mfi, GSTa),
                      statistic = list(all_continuous() ~ "{median} ({p25}, {p75}) [{min} - {max}]"),
                      missing_text = "Missing"
                    ) %>% 
                    bold_labels()

## log2 transformed
urine_subset_table<- urine_subset %>% 
                    tbl_summary(
                      include = c(Albumin, CystatinC, KIM1, Lipocalin, A1M, X2M, RBP, OPN, Uromodulin,Uromodulin_mfi,  GSTa),
                      statistic = list(all_continuous() ~ "{median} ({p25}, {p75}) [{min} - {max}]"),
                      missing_text = "Missing"
                    ) %>% 
                    bold_labels()

urine_table<- tbl_merge(tbls = list(urine_whole_table,urine_subset_table),
                              tab_spanner = c("**Whole**", "**Subset**")) %>% 
              modify_caption("**Log2-transformed Protein values**")%>%                 
              as_gt() %>%
              tab_footnote(footnote = "Exclude loss to follow-up; missing  96M urine metals; missing SES, BMI, smoking at visit, age and creatinine",
                           locations = cells_column_spanners(
                                       spanners = "**Whole**"
                            )) %>%
              tab_footnote(footnote = "Further exlude those gestational age < 37 and >42 weeks",
                           locations = cells_column_spanners(
                                       spanners =  "**Subset**"
                            ))

urine_table

```

## Plot
```{r}
# whole 
## long format
urine_whole_long<- urine_whole %>% 
                   pivot_longer(cols = c(Panel2_q_Albumin,Panel2_q_Cystatin_C,Panel1_q_KIM_1,Panel2_q_Lipocalin,Panel2_q_A1_Microglobulin,Panel3_q_X2Microglobulin,Panel3_q_RBP,Panel2_q_OPN,Panel3_q_Uromodulin,Panel3_mfi_Uromodulin,Panel1_q_GSTa),
                   names_to = "protein",
                   values_to = "protein_value",
                   values_drop_na = FALSE)
## transformed
protein_plot1 <- ggplot(urine_whole_long, aes(x=log2(protein_value))) + 
    geom_histogram() +
    facet_wrap(~protein, scale="free") +
    scale_x_continuous(name="Concentration (ng/ml)")+
    labs(title="Whole")

# subset
## long format
urine_subset_long<- urine_subset %>% 
                   pivot_longer(cols = c(Panel2_q_Albumin,Panel2_q_Cystatin_C,Panel1_q_KIM_1,Panel2_q_Lipocalin,Panel2_q_A1_Microglobulin,Panel3_q_X2Microglobulin,Panel3_q_RBP,Panel2_q_OPN,Panel3_q_Uromodulin,Panel3_mfi_Uromodulin,Panel1_q_GSTa),
                   names_to = "protein",
                   values_to = "protein_value",
                   values_drop_na = FALSE)
## transformed
protein_plot2 <- ggplot(urine_subset_long, aes(x=log2(protein_value))) + 
    geom_histogram() +
    facet_wrap(~protein, scale="free") +
    scale_x_continuous(name="Concentration (ng/ml)")+
    labs(title="Subset")

# combine

protein_plot<- ggarrange(protein_plot1, protein_plot2,
                         nrow=1, ncol=2)+
               labs(title="Histogram for each protein absolute quantification (Log 2 transformation)")

protein_plot





```



# Urine metal mixture (metals/CRE) vs. Kidney injury biomarker: +, rh=100, adjusted for CRE
```{r}
# specify metal mixture
mixture_adj=names(urine_whole[,c("As_adjCRE","Cd_adjCRE","Pb_adjCRE","Hg_adjCRE","Cu_adjCRE","Zn_adjCRE")])
mixture_adj

# specify protein biomarkers
protein_variable=names(urine_whole[,c("Albumin", "CystatinC", "KIM1", "Lipocalin", "A1M", "X2M", "RBP", "OPN", "Uromodulin_mfi", "GSTa")])
protein_variable
protein_data=urine_whole[,c("Albumin", "CystatinC", "KIM1", "Lipocalin", "A1M", "X2M", "RBP", "OPN", "Uromodulin_mfi", "GSTa")]

```


```{r, warning=FALSE, message=FALSE}

## Fit the models
    urine_whole_nomiss<- list()
    wqs_pos_10_results<- list()
    number_obs<- vector()
    for (i in 1:length(protein_data)){
      
    ### 1. adjust analysis dataset - restricted to subject who have no missing values and both measurements
    urine_whole_nomiss[[i]]<- urine_whole %>% 
                              filter(is.na(protein_data[,i])==FALSE) 
    
    ## 2. fitting models
    protein_i<- colnames(protein_data)[i]
    wqs_pos_10_results[[i]]<- gwqsrh(as.formula(paste0(protein_i, " ~ wqs +
                                              as.factor(SES_3cat2T) + child_age96 + as.factor(sexo_h00) + 
                                              as.factor(smoke_inside96) + `_ZBFA96` + h_crea_ur96")),
                                     data = urine_whole_nomiss[[i]],
                                     mix_name = mixture_adj, q = 4,
                                     validation = 0.6,rh = 100, b = 100, rs= FALSE, 
                                     b1_pos = TRUE, b1_constr = TRUE, family = "gaussian",
                                     seed = 63256, signal="t2")
    
    ## 3. number of obs
    number_obs[i]<- nrow(urine_whole_nomiss[[i]])
    }

```


```{r}

## Part1: extract estimate w/ 95% CI from models
### extract results to a list
wqs_pos_10_results_summary<- lapply(wqs_pos_10_results, summary)
wqs_pos_10_results_coefs<- lapply(wqs_pos_10_results_summary, coefficients)

predictor<- c("Intercept", "wqs", "SES_2", "SES_3", "child_age96", "sex_2", "smoking_1", "bmi96", "CRE")

### add number of obs
for (i in 1:length(protein_data)){
  wqs_pos_10_results_coefs[[i]]<- data.frame(wqs_pos_10_results_coefs[[i]], predictor) %>% 
                                  mutate(obs=number_obs[i])}
### add outcome variables
names(wqs_pos_10_results_coefs) <- protein_variable

### combine results into one dataframe
wqs_pos_10_results_coefs_data1 <- bind_rows(wqs_pos_10_results_coefs, .id = "protein_variable")

### refine results in data
wqs_pos_10_results_coefs_data <- wqs_pos_10_results_coefs_data1 %>% 
                           filter(predictor == "wqs") %>% 
                           mutate(Estimate = format(round(Estimate, 3), nsmall = 3),
                                  conf.low = format(round(X2.5.., 3), nsmall = 3),
                                  conf.high = format(round(X97.5.., 3), nsmall = 3)) %>% 
                           unite("CI", c("conf.low", "conf.high"), sep=", ") %>% 
                           select(protein_variable, obs, predictor, Estimate,  CI) 



## Part2: extract weights from models
wqs_pos_10_results_weights<- list()

for (i in 1:length(protein_data)){
  wqs_pos_10_results_weights[[i]]<- data.frame(wqs_pos_10_results[[i]]$final_weights)
}

### add outcome variables
names(wqs_pos_10_results_weights) <- protein_variable

### combine results into one dataframe
wqs_pos_10_results_weights_data <- bind_rows(wqs_pos_10_results_weights, .id = "protein_variable") %>% 
                                   mutate(Weight_Estimate = format(round(Estimate, 3), nsmall = 3),
                                          conf.low = format(round(X2.5.., 3), nsmall = 3),
                                          conf.high = format(round(X97.5., 3), nsmall = 3)) %>% 
                                   unite("Weight_CI", c("conf.low", "conf.high"), sep=", ") %>% 
                                   select(protein_variable, mix_name, Weight_Estimate,  Weight_CI)  
                                   

wqs_pos_10_results_info<- wqs_pos_10_results_coefs_data %>% 
                          left_join(wqs_pos_10_results_weights_data, by="protein_variable", na_matches = "never")

wqs_pos_10_results_info[2:6, 1:5]<- NA
wqs_pos_10_results_info[8:12, 1:5]<- NA
wqs_pos_10_results_info[14:18, 1:5]<- NA
wqs_pos_10_results_info[20:24, 1:5]<- NA
wqs_pos_10_results_info[26:30, 1:5]<- NA
wqs_pos_10_results_info[32:36, 1:5]<- NA
wqs_pos_10_results_info[38:42, 1:5]<- NA
wqs_pos_10_results_info[44:48, 1:5]<- NA
wqs_pos_10_results_info[50:54, 1:5]<- NA
wqs_pos_10_results_info[56:60, 1:5]<- NA


### put result into one table
tabel<- flextable(wqs_pos_10_results_info) %>% 
        add_header_lines("Positive association, Repearted hold out = 100") %>% 
        set_header_labels(Estimate.x="Estimate", mix_name="Metal name", Estimate.y="Weight (mean)",X2.5..="Weight (conf.low)",X97.5.="Weight (conf.high)") %>% 
        theme_box()
tabel



```





